// This file is auto-generated by @hey-api/openapi-ts

export const BusinessTypeSchema = {
    type: 'string',
    enum: [
        'almacen',
        'kiosco',
        'ferreteria',
        'barberia',
        'restaurante',
        'tienda_ropa',
        'tienda_electronica',
        'otro'
    ]
} as const;

export const PlanSchema = {
    type: 'string',
    enum: [
        'basic',
        'pro',
        'enterprise'
    ]
} as const;

export const CreateTenantDtoSchema = {
    type: 'object',
    properties: {
        businessType: {
            allOf: [
                {
                    $ref: '#/components/schemas/BusinessType'
                }
            ]
        },
        plan: {
            allOf: [
                {
                    $ref: '#/components/schemas/Plan'
                }
            ]
        },
        businessName: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        ownerEmail: {
            type: 'string',
            format: 'email'
        }
    },
    required: [
        'businessName',
        'ownerEmail'
    ]
} as const;

export const UpdateTenantDtoSchema = {
    type: 'object',
    properties: {
        plan: {
            allOf: [
                {
                    $ref: '#/components/schemas/Plan'
                }
            ]
        },
        name: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        }
    }
} as const;

export const UserSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        password: {
            type: 'string',
            nullable: true
        },
        avatarUrl: {
            type: 'string',
            nullable: true
        },
        expoPushToken: {
            type: 'string',
            nullable: true
        },
        globalRole: {
            type: 'string',
            enum: [
                'admin',
                'user'
            ]
        },
        isActive: {
            type: 'boolean'
        },
        memberships: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TenantMembership'
            }
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'email',
        'password',
        'avatarUrl',
        'expoPushToken',
        'globalRole',
        'isActive',
        'memberships',
        'createdAt'
    ]
} as const;

export const TenantSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        businessType: {
            enum: [
                'almacen',
                'kiosco',
                'ferreteria',
                'barberia',
                'restaurante',
                'tienda_ropa',
                'tienda_electronica',
                'otro'
            ],
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        plan: {
            enum: [
                'basic',
                'pro',
                'enterprise'
            ],
            type: 'string'
        },
        isOnboarded: {
            type: 'boolean'
        },
        isActive: {
            type: 'boolean'
        },
        staffModules: {
            nullable: true,
            type: 'array',
            items: {
                type: 'string'
            }
        },
        memberships: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TenantMembership'
            }
        },
        trialEndsAt: {
            format: 'date-time',
            type: 'string',
            nullable: true
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'businessType',
        'phone',
        'plan',
        'isOnboarded',
        'isActive',
        'staffModules',
        'memberships',
        'trialEndsAt',
        'createdAt'
    ]
} as const;

export const TenantMembershipSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        user: {
            $ref: '#/components/schemas/User'
        },
        tenantId: {
            type: 'string'
        },
        tenant: {
            $ref: '#/components/schemas/Tenant'
        },
        role: {
            type: 'string',
            enum: [
                'owner',
                'staff'
            ]
        },
        isActive: {
            type: 'boolean'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'userId',
        'user',
        'tenantId',
        'tenant',
        'role',
        'isActive',
        'createdAt'
    ]
} as const;

export const LoginDtoSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        password: {
            type: 'string',
            minLength: 6
        }
    },
    required: [
        'email',
        'password'
    ]
} as const;

export const OnboardingDtoSchema = {
    type: 'object',
    properties: {
        businessType: {
            allOf: [
                {
                    $ref: '#/components/schemas/BusinessType'
                }
            ]
        },
        businessName: {
            type: 'string',
            maxLength: 100
        },
        phone: {
            type: 'string',
            maxLength: 30
        }
    }
} as const;

export const AddMemberDtoSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        name: {
            type: 'string',
            minLength: 2
        },
        role: {
            type: 'string',
            enum: [
                'owner',
                'staff'
            ]
        },
        resend: {
            type: 'boolean'
        }
    },
    required: [
        'email'
    ]
} as const;

export const UpdateMemberDtoSchema = {
    type: 'object',
    properties: {
        role: {
            type: 'string',
            enum: [
                'owner',
                'staff'
            ]
        },
        name: {
            type: 'string',
            minLength: 2
        }
    }
} as const;

export const UpdateProfileDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        }
    },
    required: [
        'name'
    ]
} as const;

export const ChangePasswordDtoSchema = {
    type: 'object',
    properties: {
        currentPassword: {
            type: 'string'
        },
        newPassword: {
            type: 'string',
            minLength: 6
        }
    },
    required: [
        'currentPassword',
        'newPassword'
    ]
} as const;

export const SavePushTokenDtoSchema = {
    type: 'object',
    properties: {
        token: {
            type: 'string',
            nullable: true,
            default: null
        }
    },
    required: [
        'token'
    ]
} as const;

export const AcceptInvitationDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 2
        },
        password: {
            type: 'string',
            minLength: 6
        }
    },
    required: [
        'name',
        'password'
    ]
} as const;

export const CreateMessageDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        businessType: {
            type: 'string',
            maxLength: 100
        },
        phone: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: [
        'name',
        'email',
        'businessType',
        'message'
    ]
} as const;

export const UpdateMessageDtoSchema = {
    type: 'object',
    properties: {
        status: {
            type: 'string',
            enum: [
                'pending',
                'read',
                'replied',
                'snoozed',
                'dismissed'
            ]
        },
        isUser: {
            type: 'boolean'
        },
        notes: {
            type: 'string'
        }
    }
} as const;

export const ContactMessageSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        businessType: {
            type: 'string',
            nullable: true
        },
        phone: {
            type: 'string'
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: [
                'pending',
                'read',
                'replied',
                'snoozed',
                'dismissed'
            ]
        },
        isUser: {
            type: 'boolean'
        },
        notes: {
            type: 'string'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'email',
        'businessType',
        'phone',
        'message',
        'status',
        'isUser',
        'notes',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const UpsertNotificationSettingsDtoSchema = {
    type: 'object',
    properties: {
        whatsappPhone: {
            type: 'string',
            nullable: true
        },
        whatsappOptIn: {
            type: 'boolean'
        },
        alertLowStock: {
            type: 'boolean'
        },
        alertNewSale: {
            type: 'boolean'
        },
        alertTurnAssigned: {
            type: 'boolean'
        }
    }
} as const;

export const NotificationSettingsSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        tenantId: {
            type: 'string'
        },
        whatsappPhone: {
            type: 'string',
            nullable: true
        },
        whatsappOptIn: {
            type: 'boolean'
        },
        alertLowStock: {
            type: 'boolean'
        },
        alertNewSale: {
            type: 'boolean'
        },
        alertTurnAssigned: {
            type: 'boolean'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'tenantId',
        'whatsappPhone',
        'whatsappOptIn',
        'alertLowStock',
        'alertNewSale',
        'alertTurnAssigned',
        'updatedAt'
    ]
} as const;

export const NotificationSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        tenantId: {
            type: 'string'
        },
        type: {
            type: 'string',
            enum: [
                'low_stock',
                'new_sale',
                'turn_assigned'
            ]
        },
        title: {
            type: 'string'
        },
        body: {
            type: 'string'
        },
        read: {
            type: 'boolean'
        },
        data: {
            type: 'object',
            nullable: true
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'tenantId',
        'type',
        'title',
        'body',
        'read',
        'data',
        'createdAt'
    ]
} as const;

export const CreateCategoryDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    },
    required: [
        'name'
    ]
} as const;

export const CategorySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        tenantId: {
            type: 'string'
        },
        tenant: {
            $ref: '#/components/schemas/Tenant'
        },
        products: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Product'
            }
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'description',
        'tenantId',
        'tenant',
        'products',
        'createdAt'
    ]
} as const;

export const ProductSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        costPrice: {
            type: 'number'
        },
        salePrice: {
            type: 'number'
        },
        stock: {
            type: 'number'
        },
        minStock: {
            type: 'number'
        },
        imageUrl: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        },
        categoryId: {
            type: 'string',
            nullable: true
        },
        category: {
            nullable: true,
            type: 'object',
            allOf: [
                {
                    $ref: '#/components/schemas/Category'
                }
            ]
        },
        tenantId: {
            type: 'string'
        },
        tenant: {
            $ref: '#/components/schemas/Tenant'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'description',
        'code',
        'costPrice',
        'salePrice',
        'stock',
        'minStock',
        'imageUrl',
        'isActive',
        'categoryId',
        'category',
        'tenantId',
        'tenant',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const UpdateCategoryDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateProductDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        costPrice: {
            type: 'number',
            minimum: 0
        },
        salePrice: {
            type: 'number',
            minimum: 0
        },
        stock: {
            type: 'number',
            minimum: 0
        },
        minStock: {
            type: 'number',
            minimum: 0
        },
        imageUrl: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        },
        categoryId: {
            type: 'string'
        }
    },
    required: [
        'name',
        'code'
    ]
} as const;

export const UpdateProductDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        costPrice: {
            type: 'number',
            minimum: 0
        },
        salePrice: {
            type: 'number',
            minimum: 0
        },
        minStock: {
            type: 'number',
            minimum: 0
        },
        imageUrl: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        },
        categoryId: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const SaleItemDtoSchema = {
    type: 'object',
    properties: {
        productId: {
            type: 'string',
            format: 'uuid'
        },
        description: {
            type: 'string',
            maxLength: 200
        },
        unitPrice: {
            type: 'number',
            minimum: 0
        },
        quantity: {
            type: 'number',
            minimum: 1
        }
    },
    required: [
        'quantity'
    ]
} as const;

export const CreateSaleDtoSchema = {
    type: 'object',
    properties: {
        items: {
            minItems: 1,
            type: 'array',
            items: {
                $ref: '#/components/schemas/SaleItemDto'
            }
        },
        paymentMethod: {
            type: 'string',
            enum: [
                'cash',
                'card',
                'transfer'
            ]
        },
        notes: {
            type: 'string'
        },
        customDate: {
            type: 'string'
        },
        discountPct: {
            type: 'number',
            minimum: 0,
            maximum: 100
        }
    },
    required: [
        'items',
        'paymentMethod'
    ]
} as const;

export const SaleSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        total: {
            type: 'number'
        },
        profit: {
            type: 'number'
        },
        paymentMethod: {
            enum: [
                'cash',
                'card',
                'transfer'
            ],
            type: 'string'
        },
        notes: {
            type: 'string'
        },
        itemCount: {
            type: 'number'
        },
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/SaleItem'
            }
        },
        tenantId: {
            type: 'string'
        },
        tenant: {
            $ref: '#/components/schemas/Tenant'
        },
        userId: {
            type: 'string'
        },
        user: {
            $ref: '#/components/schemas/User'
        },
        saleNumber: {
            type: 'number'
        },
        discount: {
            type: 'number'
        },
        refundedAt: {
            format: 'date-time',
            type: 'string',
            nullable: true
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'total',
        'profit',
        'paymentMethod',
        'notes',
        'itemCount',
        'items',
        'tenantId',
        'tenant',
        'userId',
        'user',
        'saleNumber',
        'discount',
        'refundedAt',
        'createdAt'
    ]
} as const;

export const SaleItemSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        saleId: {
            type: 'string'
        },
        sale: {
            $ref: '#/components/schemas/Sale'
        },
        productId: {
            type: 'string',
            nullable: true
        },
        product: {
            nullable: true,
            type: 'object',
            allOf: [
                {
                    $ref: '#/components/schemas/Product'
                }
            ]
        },
        description: {
            type: 'string',
            nullable: true
        },
        quantity: {
            type: 'number'
        },
        unitPrice: {
            type: 'number'
        },
        costPrice: {
            type: 'number'
        },
        refundedQuantity: {
            type: 'number'
        }
    },
    required: [
        'id',
        'saleId',
        'sale',
        'productId',
        'product',
        'description',
        'quantity',
        'unitPrice',
        'costPrice',
        'refundedQuantity'
    ]
} as const;

export const PartialRefundItemDtoSchema = {
    type: 'object',
    properties: {
        saleItemId: {
            type: 'string',
            format: 'uuid'
        },
        quantity: {
            type: 'number',
            minimum: 1
        }
    },
    required: [
        'saleItemId',
        'quantity'
    ]
} as const;

export const PartialRefundDtoSchema = {
    type: 'object',
    properties: {
        items: {
            minItems: 1,
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartialRefundItemDto'
            }
        }
    },
    required: [
        'items'
    ]
} as const;

export const CreateStockMovementDtoSchema = {
    type: 'object',
    properties: {
        productId: {
            type: 'string',
            format: 'uuid'
        },
        type: {
            type: 'string',
            enum: [
                'entry',
                'exit',
                'adjustment'
            ]
        },
        quantity: {
            type: 'number',
            minimum: 0
        },
        reason: {
            type: 'string',
            maxLength: 255
        }
    },
    required: [
        'productId',
        'type',
        'quantity',
        'reason'
    ]
} as const;

export const StockMovementSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        type: {
            type: 'string',
            enum: [
                'entry',
                'exit',
                'adjustment'
            ]
        },
        quantity: {
            type: 'number'
        },
        reason: {
            type: 'string'
        },
        stockBefore: {
            type: 'number'
        },
        stockAfter: {
            type: 'number'
        },
        productId: {
            type: 'string'
        },
        product: {
            $ref: '#/components/schemas/Product'
        },
        tenantId: {
            type: 'string'
        },
        tenant: {
            $ref: '#/components/schemas/Tenant'
        },
        userId: {
            type: 'string'
        },
        user: {
            $ref: '#/components/schemas/User'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'type',
        'quantity',
        'reason',
        'stockBefore',
        'stockAfter',
        'productId',
        'product',
        'tenantId',
        'tenant',
        'userId',
        'user',
        'createdAt'
    ]
} as const;

export const TurnSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        clientName: {
            type: 'string'
        },
        clientPhone: {
            type: 'string'
        },
        service: {
            type: 'string'
        },
        startTime: {
            format: 'date-time',
            type: 'string',
            nullable: true
        },
        date: {
            type: 'string'
        },
        duration: {
            type: 'number'
        },
        price: {
            type: 'number',
            nullable: true
        },
        status: {
            enum: [
                'pending',
                'in_progress',
                'done',
                'cancelled',
                'no_show'
            ],
            type: 'string'
        },
        notes: {
            type: 'string'
        },
        tenantId: {
            type: 'string'
        },
        tenant: {
            $ref: '#/components/schemas/Tenant'
        },
        assignedUserId: {
            type: 'string'
        },
        assignedUser: {
            nullable: true,
            type: 'object',
            allOf: [
                {
                    $ref: '#/components/schemas/User'
                }
            ]
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'clientName',
        'clientPhone',
        'service',
        'startTime',
        'date',
        'duration',
        'price',
        'status',
        'notes',
        'tenantId',
        'tenant',
        'assignedUserId',
        'assignedUser',
        'createdAt'
    ]
} as const;

export const CreateTurnDtoSchema = {
    type: 'object',
    properties: {
        clientName: {
            type: 'string'
        },
        clientPhone: {
            type: 'string',
            nullable: true
        },
        service: {
            type: 'string'
        },
        startTime: {
            type: 'string',
            nullable: true
        },
        date: {
            type: 'string'
        },
        duration: {
            type: 'number',
            minimum: 5,
            maximum: 480
        },
        notes: {
            type: 'string',
            nullable: true
        },
        assignedUserId: {
            type: 'string',
            nullable: true,
            format: 'uuid'
        },
        price: {
            type: 'number',
            nullable: true,
            minimum: 0
        }
    },
    required: [
        'clientName',
        'service',
        'duration'
    ]
} as const;

export const UpdateTurnDtoSchema = {
    type: 'object',
    properties: {
        clientName: {
            type: 'string'
        },
        clientPhone: {
            type: 'string',
            nullable: true
        },
        service: {
            type: 'string'
        },
        startTime: {
            type: 'string',
            nullable: true
        },
        date: {
            type: 'string'
        },
        duration: {
            type: 'number',
            minimum: 5,
            maximum: 480
        },
        notes: {
            type: 'string',
            nullable: true
        },
        assignedUserId: {
            type: 'string',
            nullable: true,
            format: 'uuid'
        },
        price: {
            type: 'number',
            nullable: true,
            minimum: 0
        },
        status: {
            type: 'string',
            enum: [
                'pending',
                'in_progress',
                'done',
                'cancelled',
                'no_show'
            ]
        }
    }
} as const;
