// This file is auto-generated by @hey-api/openapi-ts

export const BusinessTypeSchema = {
    type: 'string',
    enum: [
        'almacen',
        'kiosco',
        'ferreteria',
        'barberia',
        'restaurante',
        'tienda_ropa',
        'tienda_electronica'
    ]
} as const;

export const PlanSchema = {
    type: 'string',
    enum: [
        'basic',
        'pro',
        'enterprise'
    ]
} as const;

export const CreateTenantDtoSchema = {
    type: 'object',
    properties: {
        businessType: {
            allOf: [
                {
                    $ref: '#/components/schemas/BusinessType'
                }
            ]
        },
        plan: {
            allOf: [
                {
                    $ref: '#/components/schemas/Plan'
                }
            ]
        },
        businessName: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        ownerEmail: {
            type: 'string',
            format: 'email'
        }
    },
    required: [
        'businessName',
        'ownerEmail'
    ]
} as const;

export const UpdateTenantDtoSchema = {
    type: 'object',
    properties: {
        plan: {
            allOf: [
                {
                    $ref: '#/components/schemas/Plan'
                }
            ]
        },
        name: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        }
    }
} as const;

export const UserSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        password: {
            type: 'string',
            nullable: true
        },
        avatarUrl: {
            type: 'string',
            nullable: true
        },
        globalRole: {
            type: 'string',
            enum: [
                'admin',
                'user'
            ]
        },
        isActive: {
            type: 'boolean'
        },
        memberships: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TenantMembership'
            }
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'email',
        'password',
        'avatarUrl',
        'globalRole',
        'isActive',
        'memberships',
        'createdAt'
    ]
} as const;

export const TenantSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        businessType: {
            enum: [
                'almacen',
                'kiosco',
                'ferreteria',
                'barberia',
                'restaurante',
                'tienda_ropa',
                'tienda_electronica'
            ],
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        plan: {
            enum: [
                'basic',
                'pro',
                'enterprise'
            ],
            type: 'string'
        },
        isOnboarded: {
            type: 'boolean'
        },
        isActive: {
            type: 'boolean'
        },
        memberships: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TenantMembership'
            }
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'businessType',
        'phone',
        'plan',
        'isOnboarded',
        'isActive',
        'memberships',
        'createdAt'
    ]
} as const;

export const TenantMembershipSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        user: {
            $ref: '#/components/schemas/User'
        },
        tenantId: {
            type: 'string'
        },
        tenant: {
            $ref: '#/components/schemas/Tenant'
        },
        role: {
            type: 'string',
            enum: [
                'owner',
                'staff'
            ]
        },
        isActive: {
            type: 'boolean'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'userId',
        'user',
        'tenantId',
        'tenant',
        'role',
        'isActive',
        'createdAt'
    ]
} as const;

export const LoginDtoSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        password: {
            type: 'string',
            minLength: 6
        }
    },
    required: [
        'email',
        'password'
    ]
} as const;

export const OnboardingDtoSchema = {
    type: 'object',
    properties: {
        businessType: {
            allOf: [
                {
                    $ref: '#/components/schemas/BusinessType'
                }
            ]
        },
        businessName: {
            type: 'string',
            maxLength: 100
        },
        phone: {
            type: 'string',
            maxLength: 30
        }
    },
    required: [
        'businessType'
    ]
} as const;

export const AddMemberDtoSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        name: {
            type: 'string',
            minLength: 2
        },
        role: {
            type: 'string',
            enum: [
                'owner',
                'staff'
            ]
        },
        resend: {
            type: 'boolean'
        }
    },
    required: [
        'email'
    ]
} as const;

export const UpdateMemberDtoSchema = {
    type: 'object',
    properties: {
        role: {
            type: 'string',
            enum: [
                'owner',
                'staff'
            ]
        },
        name: {
            type: 'string',
            minLength: 2
        }
    }
} as const;

export const UpdateProfileDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        }
    },
    required: [
        'name'
    ]
} as const;

export const ChangePasswordDtoSchema = {
    type: 'object',
    properties: {
        currentPassword: {
            type: 'string'
        },
        newPassword: {
            type: 'string',
            minLength: 6
        }
    },
    required: [
        'currentPassword',
        'newPassword'
    ]
} as const;

export const AcceptInvitationDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 2
        },
        password: {
            type: 'string',
            minLength: 6
        }
    },
    required: [
        'name',
        'password'
    ]
} as const;

export const CreateMessageDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        businessType: {
            type: 'string',
            maxLength: 100
        },
        phone: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: [
        'name',
        'email',
        'businessType',
        'message'
    ]
} as const;

export const UpdateMessageDtoSchema = {
    type: 'object',
    properties: {
        status: {
            type: 'string',
            enum: [
                'pending',
                'read',
                'replied',
                'snoozed',
                'dismissed'
            ]
        },
        isUser: {
            type: 'boolean'
        },
        notes: {
            type: 'string'
        }
    }
} as const;

export const ContactMessageSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        businessType: {
            type: 'string',
            nullable: true
        },
        phone: {
            type: 'string'
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: [
                'pending',
                'read',
                'replied',
                'snoozed',
                'dismissed'
            ]
        },
        isUser: {
            type: 'boolean'
        },
        notes: {
            type: 'string'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'email',
        'businessType',
        'phone',
        'message',
        'status',
        'isUser',
        'notes',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const CreateCategoryDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    },
    required: [
        'name'
    ]
} as const;

export const CategorySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        tenantId: {
            type: 'string'
        },
        tenant: {
            $ref: '#/components/schemas/Tenant'
        },
        products: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Product'
            }
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'description',
        'tenantId',
        'tenant',
        'products',
        'createdAt'
    ]
} as const;

export const ProductSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        costPrice: {
            type: 'number'
        },
        salePrice: {
            type: 'number'
        },
        stock: {
            type: 'number'
        },
        minStock: {
            type: 'number'
        },
        imageUrl: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        },
        categoryId: {
            type: 'string',
            nullable: true
        },
        category: {
            nullable: true,
            type: 'object',
            allOf: [
                {
                    $ref: '#/components/schemas/Category'
                }
            ]
        },
        tenantId: {
            type: 'string'
        },
        tenant: {
            $ref: '#/components/schemas/Tenant'
        },
        createdAt: {
            format: 'date-time',
            type: 'string'
        },
        updatedAt: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: [
        'id',
        'name',
        'description',
        'code',
        'costPrice',
        'salePrice',
        'stock',
        'minStock',
        'imageUrl',
        'isActive',
        'categoryId',
        'category',
        'tenantId',
        'tenant',
        'createdAt',
        'updatedAt'
    ]
} as const;

export const UpdateCategoryDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateProductDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        costPrice: {
            type: 'number',
            minimum: 0
        },
        salePrice: {
            type: 'number',
            minimum: 0
        },
        stock: {
            type: 'number',
            minimum: 0
        },
        minStock: {
            type: 'number',
            minimum: 0
        },
        imageUrl: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        },
        categoryId: {
            type: 'string'
        }
    },
    required: [
        'name',
        'code'
    ]
} as const;

export const UpdateProductDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        code: {
            type: 'string'
        },
        costPrice: {
            type: 'number',
            minimum: 0
        },
        salePrice: {
            type: 'number',
            minimum: 0
        },
        stock: {
            type: 'number',
            minimum: 0
        },
        minStock: {
            type: 'number',
            minimum: 0
        },
        imageUrl: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        },
        categoryId: {
            type: 'string',
            nullable: true
        }
    }
} as const;
