// This file is auto-generated by @hey-api/openapi-ts

export const CreateTenantDtoSchema = {
    type: 'object',
    properties: {}
} as const;

export const UpdateTenantDtoSchema = {
    type: 'object',
    properties: {}
} as const;

export const OnboardingDtoSchema = {
    type: 'object',
    properties: {}
} as const;

export const RegisterDtoSchema = {
    type: 'object',
    properties: {}
} as const;

export const LoginDtoSchema = {
    type: 'object',
    properties: {}
} as const;

export const CreateCategoryDtoSchema = {
    type: 'object',
    properties: {}
} as const;

export const UpdateCategoryDtoSchema = {
    type: 'object',
    properties: {}
} as const;

export const CreateProductDtoSchema = {
    type: 'object',
    properties: {}
} as const;

export const UpdateProductDtoSchema = {
    type: 'object',
    properties: {}
} as const;
