// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AdminControllerCreateTenantData, AdminControllerCreateTenantResponses, AdminControllerDeleteTenantData, AdminControllerDeleteTenantResponses, AdminControllerFindAllTenantsData, AdminControllerFindAllTenantsResponses, AdminControllerUpdateTenantData, AdminControllerUpdateTenantResponses, AuthControllerLoginData, AuthControllerLoginResponses, AuthControllerMeData, AuthControllerMeResponses, AuthControllerRegisterData, AuthControllerRegisterResponses, CategoriesControllerCreateData, CategoriesControllerCreateResponses, CategoriesControllerFindAllData, CategoriesControllerFindAllResponses, CategoriesControllerFindOneData, CategoriesControllerFindOneResponses, CategoriesControllerRemoveData, CategoriesControllerRemoveResponses, CategoriesControllerUpdateData, CategoriesControllerUpdateResponses, ProductsControllerCreateData, ProductsControllerCreateResponses, ProductsControllerFindAllData, ProductsControllerFindAllResponses, ProductsControllerFindLowStockData, ProductsControllerFindLowStockResponses, ProductsControllerFindOneData, ProductsControllerFindOneResponses, ProductsControllerRemoveData, ProductsControllerRemoveResponses, ProductsControllerUpdateData, ProductsControllerUpdateResponses, TenantsControllerCompleteOnboardingData, TenantsControllerCompleteOnboardingResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const adminControllerFindAllTenants = <ThrowOnError extends boolean = false>(options?: Options<AdminControllerFindAllTenantsData, ThrowOnError>) => (options?.client ?? client).get<AdminControllerFindAllTenantsResponses, unknown, ThrowOnError>({ url: '/admin/tenants', ...options });

export const adminControllerCreateTenant = <ThrowOnError extends boolean = false>(options: Options<AdminControllerCreateTenantData, ThrowOnError>) => (options.client ?? client).post<AdminControllerCreateTenantResponses, unknown, ThrowOnError>({
    url: '/admin/tenants',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const adminControllerDeleteTenant = <ThrowOnError extends boolean = false>(options: Options<AdminControllerDeleteTenantData, ThrowOnError>) => (options.client ?? client).delete<AdminControllerDeleteTenantResponses, unknown, ThrowOnError>({ url: '/admin/tenants/{id}', ...options });

export const adminControllerUpdateTenant = <ThrowOnError extends boolean = false>(options: Options<AdminControllerUpdateTenantData, ThrowOnError>) => (options.client ?? client).patch<AdminControllerUpdateTenantResponses, unknown, ThrowOnError>({
    url: '/admin/tenants/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const tenantsControllerCompleteOnboarding = <ThrowOnError extends boolean = false>(options: Options<TenantsControllerCompleteOnboardingData, ThrowOnError>) => (options.client ?? client).patch<TenantsControllerCompleteOnboardingResponses, unknown, ThrowOnError>({
    url: '/tenants/onboarding',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authControllerRegister = <ThrowOnError extends boolean = false>(options: Options<AuthControllerRegisterData, ThrowOnError>) => (options.client ?? client).post<AuthControllerRegisterResponses, unknown, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authControllerLogin = <ThrowOnError extends boolean = false>(options: Options<AuthControllerLoginData, ThrowOnError>) => (options.client ?? client).post<AuthControllerLoginResponses, unknown, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authControllerMe = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerMeData, ThrowOnError>) => (options?.client ?? client).get<AuthControllerMeResponses, unknown, ThrowOnError>({ url: '/auth/me', ...options });

export const categoriesControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<CategoriesControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<CategoriesControllerFindAllResponses, unknown, ThrowOnError>({ url: '/categories', ...options });

export const categoriesControllerCreate = <ThrowOnError extends boolean = false>(options: Options<CategoriesControllerCreateData, ThrowOnError>) => (options.client ?? client).post<CategoriesControllerCreateResponses, unknown, ThrowOnError>({
    url: '/categories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const categoriesControllerRemove = <ThrowOnError extends boolean = false>(options: Options<CategoriesControllerRemoveData, ThrowOnError>) => (options.client ?? client).delete<CategoriesControllerRemoveResponses, unknown, ThrowOnError>({ url: '/categories/{id}', ...options });

export const categoriesControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<CategoriesControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<CategoriesControllerFindOneResponses, unknown, ThrowOnError>({ url: '/categories/{id}', ...options });

export const categoriesControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<CategoriesControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<CategoriesControllerUpdateResponses, unknown, ThrowOnError>({
    url: '/categories/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const productsControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<ProductsControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<ProductsControllerFindAllResponses, unknown, ThrowOnError>({ url: '/products', ...options });

export const productsControllerCreate = <ThrowOnError extends boolean = false>(options: Options<ProductsControllerCreateData, ThrowOnError>) => (options.client ?? client).post<ProductsControllerCreateResponses, unknown, ThrowOnError>({
    url: '/products',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const productsControllerFindLowStock = <ThrowOnError extends boolean = false>(options?: Options<ProductsControllerFindLowStockData, ThrowOnError>) => (options?.client ?? client).get<ProductsControllerFindLowStockResponses, unknown, ThrowOnError>({ url: '/products/low-stock', ...options });

export const productsControllerRemove = <ThrowOnError extends boolean = false>(options: Options<ProductsControllerRemoveData, ThrowOnError>) => (options.client ?? client).delete<ProductsControllerRemoveResponses, unknown, ThrowOnError>({ url: '/products/{id}', ...options });

export const productsControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<ProductsControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<ProductsControllerFindOneResponses, unknown, ThrowOnError>({ url: '/products/{id}', ...options });

export const productsControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<ProductsControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<ProductsControllerUpdateResponses, unknown, ThrowOnError>({
    url: '/products/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
