// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CreateTenantDto = {
    [key: string]: unknown;
};

export type UpdateTenantDto = {
    [key: string]: unknown;
};

export type OnboardingDto = {
    [key: string]: unknown;
};

export type RegisterDto = {
    [key: string]: unknown;
};

export type LoginDto = {
    [key: string]: unknown;
};

export type CreateCategoryDto = {
    [key: string]: unknown;
};

export type UpdateCategoryDto = {
    [key: string]: unknown;
};

export type CreateProductDto = {
    [key: string]: unknown;
};

export type UpdateProductDto = {
    [key: string]: unknown;
};

export type AdminControllerFindAllTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/tenants';
};

export type AdminControllerFindAllTenantsResponses = {
    200: unknown;
};

export type AdminControllerCreateTenantData = {
    body: CreateTenantDto;
    path?: never;
    query?: never;
    url: '/admin/tenants';
};

export type AdminControllerCreateTenantResponses = {
    201: unknown;
};

export type AdminControllerDeleteTenantData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/tenants/{id}';
};

export type AdminControllerDeleteTenantResponses = {
    200: unknown;
};

export type AdminControllerUpdateTenantData = {
    body: UpdateTenantDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/tenants/{id}';
};

export type AdminControllerUpdateTenantResponses = {
    200: unknown;
};

export type TenantsControllerCompleteOnboardingData = {
    body: OnboardingDto;
    path?: never;
    query?: never;
    url: '/tenants/onboarding';
};

export type TenantsControllerCompleteOnboardingResponses = {
    200: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterResponses = {
    201: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    201: unknown;
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeResponses = {
    200: unknown;
};

export type CategoriesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CategoriesControllerFindAllResponses = {
    200: unknown;
};

export type CategoriesControllerCreateData = {
    body: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CategoriesControllerCreateResponses = {
    201: unknown;
};

export type CategoriesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerRemoveResponses = {
    200: unknown;
};

export type CategoriesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerFindOneResponses = {
    200: unknown;
};

export type CategoriesControllerUpdateData = {
    body: UpdateCategoryDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerUpdateResponses = {
    200: unknown;
};

export type ProductsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products';
};

export type ProductsControllerFindAllResponses = {
    200: unknown;
};

export type ProductsControllerCreateData = {
    body: CreateProductDto;
    path?: never;
    query?: never;
    url: '/products';
};

export type ProductsControllerCreateResponses = {
    201: unknown;
};

export type ProductsControllerFindLowStockData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products/low-stock';
};

export type ProductsControllerFindLowStockResponses = {
    200: unknown;
};

export type ProductsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type ProductsControllerRemoveResponses = {
    200: unknown;
};

export type ProductsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type ProductsControllerFindOneResponses = {
    200: unknown;
};

export type ProductsControllerUpdateData = {
    body: UpdateProductDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type ProductsControllerUpdateResponses = {
    200: unknown;
};
