// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export const BusinessType = {
    ALMACEN: 'almacen',
    KIOSCO: 'kiosco',
    FERRETERIA: 'ferreteria',
    BARBERIA: 'barberia',
    RESTAURANTE: 'restaurante',
    TIENDA_ROPA: 'tienda_ropa',
    TIENDA_ELECTRONICA: 'tienda_electronica',
    OTRO: 'otro'
} as const;

export type BusinessType = typeof BusinessType[keyof typeof BusinessType];

export const Plan = {
    BASIC: 'basic',
    PRO: 'pro',
    ENTERPRISE: 'enterprise'
} as const;

export type Plan = typeof Plan[keyof typeof Plan];

export type CreateTenantDto = {
    businessType?: BusinessType;
    plan?: Plan;
    businessName: string;
    phone?: string;
    ownerEmail: string;
};

export type UpdateTenantDto = {
    plan?: Plan;
    name?: string;
    phone?: string;
    isActive?: boolean;
};

export type User = {
    id: string;
    name: string;
    email: string;
    password: string | null;
    avatarUrl: string | null;
    globalRole: 'admin' | 'user';
    isActive: boolean;
    memberships: Array<TenantMembership>;
    createdAt: string;
};

export type Tenant = {
    id: string;
    name: string;
    businessType: 'almacen' | 'kiosco' | 'ferreteria' | 'barberia' | 'restaurante' | 'tienda_ropa' | 'tienda_electronica' | 'otro';
    phone: string;
    plan: 'basic' | 'pro' | 'enterprise';
    isOnboarded: boolean;
    isActive: boolean;
    staffModules: Array<string> | null;
    memberships: Array<TenantMembership>;
    createdAt: string;
};

export type TenantMembership = {
    id: string;
    userId: string;
    user: User;
    tenantId: string;
    tenant: Tenant;
    role: 'owner' | 'staff';
    isActive: boolean;
    createdAt: string;
};

export type LoginDto = {
    email: string;
    password: string;
};

export type OnboardingDto = {
    businessType: BusinessType;
    businessName?: string;
    phone?: string;
};

export type AddMemberDto = {
    email: string;
    name?: string;
    role?: 'owner' | 'staff';
    resend?: boolean;
};

export type UpdateMemberDto = {
    role?: 'owner' | 'staff';
    name?: string;
};

export type UpdateProfileDto = {
    name: string;
};

export type ChangePasswordDto = {
    currentPassword: string;
    newPassword: string;
};

export type AcceptInvitationDto = {
    name: string;
    password: string;
};

export type CreateMessageDto = {
    name: string;
    email: string;
    businessType: string;
    phone?: string;
    message: string;
};

export type UpdateMessageDto = {
    status?: 'pending' | 'read' | 'replied' | 'snoozed' | 'dismissed';
    isUser?: boolean;
    notes?: string;
};

export type ContactMessage = {
    id: string;
    name: string;
    email: string;
    businessType: string | null;
    phone: string;
    message: string;
    status: 'pending' | 'read' | 'replied' | 'snoozed' | 'dismissed';
    isUser: boolean;
    notes: string;
    createdAt: string;
    updatedAt: string;
};

export type UpsertNotificationSettingsDto = {
    whatsappPhone?: string | null;
    whatsappOptIn?: boolean;
    alertLowStock?: boolean;
};

export type NotificationSettings = {
    id: string;
    tenantId: string;
    whatsappPhone: string | null;
    whatsappOptIn: boolean;
    alertLowStock: boolean;
    updatedAt: string;
};

export type Notification = {
    id: string;
    tenantId: string;
    type: 'low_stock';
    title: string;
    body: string;
    read: boolean;
    data: {
        [key: string]: unknown;
    } | null;
    createdAt: string;
};

export type CreateCategoryDto = {
    name: string;
    description?: string;
};

export type Category = {
    id: string;
    name: string;
    description: string;
    tenantId: string;
    tenant: Tenant;
    products: Array<Product>;
    createdAt: string;
};

export type Product = {
    id: string;
    name: string;
    description: string;
    code: string;
    costPrice: number;
    salePrice: number;
    stock: number;
    minStock: number;
    imageUrl: string;
    isActive: boolean;
    categoryId: string | null;
    category: Category | null;
    tenantId: string;
    tenant: Tenant;
    createdAt: string;
    updatedAt: string;
};

export type UpdateCategoryDto = {
    name?: string;
    description?: string;
};

export type CreateProductDto = {
    name: string;
    description?: string;
    code: string;
    costPrice?: number;
    salePrice?: number;
    stock?: number;
    minStock?: number;
    imageUrl?: string;
    isActive?: boolean;
    categoryId?: string;
};

export type UpdateProductDto = {
    name?: string;
    description?: string;
    code?: string;
    costPrice?: number;
    salePrice?: number;
    minStock?: number;
    imageUrl?: string;
    isActive?: boolean;
    categoryId?: string | null;
};

export type CreateStockMovementDto = {
    productId: string;
    type: 'entry' | 'exit' | 'adjustment';
    quantity: number;
    reason: string;
};

export type StockMovement = {
    id: string;
    type: 'entry' | 'exit' | 'adjustment';
    quantity: number;
    reason: string;
    stockBefore: number;
    stockAfter: number;
    productId: string;
    product: Product;
    tenantId: string;
    tenant: Tenant;
    userId: string;
    user: User;
    createdAt: string;
};

export type AdminControllerFindAllTenantsData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        plan?: string;
        isActive?: string;
    };
    url: '/admin/tenants';
};

export type AdminControllerFindAllTenantsResponses = {
    200: unknown;
};

export type AdminControllerCreateTenantData = {
    body: CreateTenantDto;
    path?: never;
    query?: never;
    url: '/admin/tenants';
};

export type AdminControllerCreateTenantResponses = {
    201: unknown;
};

export type AdminControllerDeleteTenantData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/tenants/{id}';
};

export type AdminControllerDeleteTenantResponses = {
    200: unknown;
};

export type AdminControllerUpdateTenantData = {
    body: UpdateTenantDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/tenants/{id}';
};

export type AdminControllerUpdateTenantResponses = {
    200: Tenant;
};

export type AdminControllerUpdateTenantResponse = AdminControllerUpdateTenantResponses[keyof AdminControllerUpdateTenantResponses];

export type AdminAuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/admin/auth/login';
};

export type AdminAuthControllerLoginResponses = {
    201: unknown;
};

export type AdminAuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/auth/logout';
};

export type AdminAuthControllerLogoutResponses = {
    201: unknown;
};

export type AdminAuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/auth/me';
};

export type AdminAuthControllerMeResponses = {
    200: unknown;
};

export type TenantsControllerCompleteOnboardingData = {
    body: OnboardingDto;
    path?: never;
    query?: never;
    url: '/tenants/onboarding';
};

export type TenantsControllerCompleteOnboardingResponses = {
    200: Tenant;
};

export type TenantsControllerCompleteOnboardingResponse = TenantsControllerCompleteOnboardingResponses[keyof TenantsControllerCompleteOnboardingResponses];

export type TenantsControllerGetMembersData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        role?: string;
    };
    url: '/tenants/members';
};

export type TenantsControllerGetMembersResponses = {
    200: unknown;
};

export type TenantsControllerAddMemberData = {
    body: AddMemberDto;
    path?: never;
    query?: never;
    url: '/tenants/members';
};

export type TenantsControllerAddMemberResponses = {
    201: unknown;
};

export type TenantsControllerGetPendingInvitationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/invitations/pending';
};

export type TenantsControllerGetPendingInvitationsResponses = {
    200: unknown;
};

export type TenantsControllerRevokeInvitationData = {
    body?: never;
    path: {
        invitationId: string;
    };
    query?: never;
    url: '/tenants/invitations/pending/{invitationId}';
};

export type TenantsControllerRevokeInvitationResponses = {
    200: unknown;
};

export type TenantsControllerRemoveMemberData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/tenants/members/{userId}';
};

export type TenantsControllerRemoveMemberResponses = {
    200: unknown;
};

export type TenantsControllerUpdateMemberData = {
    body: UpdateMemberDto;
    path: {
        userId: string;
    };
    query?: never;
    url: '/tenants/members/{userId}';
};

export type TenantsControllerUpdateMemberResponses = {
    200: unknown;
};

export type TenantsControllerGetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/settings';
};

export type TenantsControllerGetSettingsResponses = {
    200: unknown;
};

export type TenantsControllerUpdateSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tenants/settings';
};

export type TenantsControllerUpdateSettingsResponses = {
    200: unknown;
};

export type UsersControllerUpdateProfileData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersControllerUpdateProfileResponses = {
    200: unknown;
};

export type UsersControllerChangePasswordData = {
    body: ChangePasswordDto;
    path?: never;
    query?: never;
    url: '/users/me/password';
};

export type UsersControllerChangePasswordResponses = {
    200: unknown;
};

export type InvitationsControllerValidateData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/invitations/validate/{token}';
};

export type InvitationsControllerValidateResponses = {
    200: unknown;
};

export type InvitationsControllerAcceptData = {
    body: AcceptInvitationDto;
    path: {
        token: string;
    };
    query?: never;
    url: '/invitations/accept/{token}';
};

export type InvitationsControllerAcceptResponses = {
    201: unknown;
};

export type InvitationsControllerGoogleStartData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/invitations/google';
};

export type InvitationsControllerGoogleStartResponses = {
    200: unknown;
};

export type InvitationsControllerGoogleCallbackData = {
    body?: never;
    path?: never;
    query: {
        code: string;
        state: string;
    };
    url: '/invitations/google/callback';
};

export type InvitationsControllerGoogleCallbackResponses = {
    200: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    201: unknown;
};

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    201: unknown;
};

export type AuthControllerSwitchTenantData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/switch-tenant';
};

export type AuthControllerSwitchTenantResponses = {
    201: unknown;
};

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeResponses = {
    200: unknown;
};

export type AuthControllerGoogleStartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type AuthControllerGoogleStartResponses = {
    200: unknown;
};

export type AuthControllerGoogleCallbackData = {
    body?: never;
    path?: never;
    query: {
        code: string;
    };
    url: '/auth/google/callback';
};

export type AuthControllerGoogleCallbackResponses = {
    200: unknown;
};

export type MessagesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        status?: Array<'pending' | 'read' | 'replied' | 'snoozed' | 'dismissed'>;
        limit?: number;
        offset?: number;
        sortBy?: string;
        sortOrder?: 'ASC' | 'DESC';
        groupBy?: string;
    };
    url: '/messages';
};

export type MessagesControllerFindAllResponses = {
    200: unknown;
};

export type MessagesControllerCreateData = {
    body: CreateMessageDto;
    path?: never;
    query?: never;
    url: '/messages';
};

export type MessagesControllerCreateResponses = {
    201: unknown;
};

export type MessagesControllerCountPendingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/messages/pending-count';
};

export type MessagesControllerCountPendingResponses = {
    200: number;
};

export type MessagesControllerCountPendingResponse = MessagesControllerCountPendingResponses[keyof MessagesControllerCountPendingResponses];

export type MessagesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/messages/{id}';
};

export type MessagesControllerRemoveResponses = {
    200: unknown;
};

export type MessagesControllerUpdateData = {
    body: UpdateMessageDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/messages/{id}';
};

export type MessagesControllerUpdateResponses = {
    200: ContactMessage;
};

export type MessagesControllerUpdateResponse = MessagesControllerUpdateResponses[keyof MessagesControllerUpdateResponses];

export type NotificationSettingsControllerGetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notification-settings';
};

export type NotificationSettingsControllerGetSettingsResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type NotificationSettingsControllerGetSettingsResponse = NotificationSettingsControllerGetSettingsResponses[keyof NotificationSettingsControllerGetSettingsResponses];

export type NotificationSettingsControllerUpsertSettingsData = {
    body: UpsertNotificationSettingsDto;
    path?: never;
    query?: never;
    url: '/notification-settings';
};

export type NotificationSettingsControllerUpsertSettingsResponses = {
    200: NotificationSettings;
};

export type NotificationSettingsControllerUpsertSettingsResponse = NotificationSettingsControllerUpsertSettingsResponses[keyof NotificationSettingsControllerUpsertSettingsResponses];

export type NotificationsControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications';
};

export type NotificationsControllerGetAllResponses = {
    200: Array<Notification>;
};

export type NotificationsControllerGetAllResponse = NotificationsControllerGetAllResponses[keyof NotificationsControllerGetAllResponses];

export type NotificationsControllerGetUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/unread-count';
};

export type NotificationsControllerGetUnreadCountResponses = {
    200: unknown;
};

export type NotificationsControllerMarkAllReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/read-all';
};

export type NotificationsControllerMarkAllReadResponses = {
    204: void;
};

export type NotificationsControllerMarkAllReadResponse = NotificationsControllerMarkAllReadResponses[keyof NotificationsControllerMarkAllReadResponses];

export type NotificationsControllerMarkReadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/notifications/{id}/read';
};

export type NotificationsControllerMarkReadResponses = {
    204: void;
};

export type NotificationsControllerMarkReadResponse = NotificationsControllerMarkReadResponses[keyof NotificationsControllerMarkReadResponses];

export type CategoriesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        hasDescription?: string;
    };
    url: '/categories';
};

export type CategoriesControllerFindAllResponses = {
    200: Array<Category>;
};

export type CategoriesControllerFindAllResponse = CategoriesControllerFindAllResponses[keyof CategoriesControllerFindAllResponses];

export type CategoriesControllerCreateData = {
    body: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/categories';
};

export type CategoriesControllerCreateResponses = {
    201: Category;
};

export type CategoriesControllerCreateResponse = CategoriesControllerCreateResponses[keyof CategoriesControllerCreateResponses];

export type CategoriesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerRemoveResponses = {
    200: unknown;
};

export type CategoriesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerFindOneResponses = {
    200: Category;
};

export type CategoriesControllerFindOneResponse = CategoriesControllerFindOneResponses[keyof CategoriesControllerFindOneResponses];

export type CategoriesControllerUpdateData = {
    body: UpdateCategoryDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/categories/{id}';
};

export type CategoriesControllerUpdateResponses = {
    200: Category;
};

export type CategoriesControllerUpdateResponse = CategoriesControllerUpdateResponses[keyof CategoriesControllerUpdateResponses];

export type ProductsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        categoryId?: string;
        isActive?: string;
        stock?: string;
    };
    url: '/products';
};

export type ProductsControllerFindAllResponses = {
    200: Array<Product>;
};

export type ProductsControllerFindAllResponse = ProductsControllerFindAllResponses[keyof ProductsControllerFindAllResponses];

export type ProductsControllerCreateData = {
    body: CreateProductDto;
    path?: never;
    query?: never;
    url: '/products';
};

export type ProductsControllerCreateResponses = {
    201: Product;
};

export type ProductsControllerCreateResponse = ProductsControllerCreateResponses[keyof ProductsControllerCreateResponses];

export type ProductsControllerFindLowStockData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products/low-stock';
};

export type ProductsControllerFindLowStockResponses = {
    200: Array<Product>;
};

export type ProductsControllerFindLowStockResponse = ProductsControllerFindLowStockResponses[keyof ProductsControllerFindLowStockResponses];

export type ProductsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type ProductsControllerRemoveResponses = {
    200: unknown;
};

export type ProductsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type ProductsControllerFindOneResponses = {
    200: Product;
};

export type ProductsControllerFindOneResponse = ProductsControllerFindOneResponses[keyof ProductsControllerFindOneResponses];

export type ProductsControllerUpdateData = {
    body: UpdateProductDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/products/{id}';
};

export type ProductsControllerUpdateResponses = {
    200: Product;
};

export type ProductsControllerUpdateResponse = ProductsControllerUpdateResponses[keyof ProductsControllerUpdateResponses];

export type StockMovementsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        productId?: string;
        type?: 'entry' | 'exit' | 'adjustment';
        limit?: number;
        offset?: number;
        sortBy?: string;
        sortOrder?: 'ASC' | 'DESC';
        groupBy?: string;
    };
    url: '/stock-movements';
};

export type StockMovementsControllerFindAllResponses = {
    200: unknown;
};

export type StockMovementsControllerCreateData = {
    body: CreateStockMovementDto;
    path?: never;
    query?: never;
    url: '/stock-movements';
};

export type StockMovementsControllerCreateResponses = {
    201: StockMovement;
};

export type StockMovementsControllerCreateResponse = StockMovementsControllerCreateResponses[keyof StockMovementsControllerCreateResponses];
